### ISSUE TITLE
Some issues about the command-line version ParaAT2.0 error

### ISSUE THREAD

**Issue by changchuanjun** [Icrus-Dev/ParaAT-2.0-Windows#1]
@Icrus-Dev 

Hi, I noticed that you have developed a Windows version of the ParaAT2.0 tool for research analysis. It's very convenient and user-friendly for beginners—great job!

However, when I use the command-line version of the ParaAT2.0 tool to execute my command, I encounter an error. Although I've tried my best to solve it, I haven't been successful. Have you ever encountered a similar issue, and do you know how to resolve it?

I am sincerely looking forward to your reply

![image](https://github.com/user-attachments/assets/b3f83abd-0dbf-4d78-97c2-e53781e2fe40)

**Comment by Icrus-Dev** [comment]
Hi!

First of all, thank you for reporting the issue. Since this is the first reported case, I'll need the file you put as input for debugging purposes.

If possible, could you please send it to my email?

**Comment by changchuanjun** [comment]
Hi，thank you for you response, I have solved this problem by changing the permissions of the software

**Comment by Icrus-Dev** [comment]
Good for you. I hope this helps you with your work!
